### ISSUE TITLE
about

### ISSUE THREAD

**Issue by wilianmaique** [ScriptedSnark/reGS_win32#3]
is this for the steam rip version?

**Comment by ScriptedSnark** [comment]
This repository is focused on Steampipe 8684 build

**Comment by wilianmaique** [comment]
would it be a no-steam version?, if so, can you send me the link? I want to test and send bugs etc, something else has to redo the serverbrowser, audio etc, like GSClient

**Comment by ScriptedSnark** [comment]
> would it be a no-steam version?, if so, can you send me the link? I want to test and send bugs etc, something else has to redo the serverbrowser, audio etc, like GSClient

Binaries are available in "Actions". If your non-steam version is Steampipe, reGS is 100% compatible.

Steam auth check is stored at hw/sw.dll (engine) anyway.

**Comment by wilianmaique** [comment]
can you send me cs 1.6 'steam pipe' download? for me to carry out tests, another thing, do you intend to create continue with the project? i can help too, in what i can

**Comment by ScriptedSnark** [comment]
> can you send me cs 1.6 'steam pipe' download? for me to carry out tests

Type "version" in console and just send output there. I think that binaries will work with your engine version.

> another thing, do you intend to create continue with the project? i can help too, in what i can

I'm making reGS with full enthusiasm but I don't have good skill for faster development. I'll continue to make reGS but I don't think that will be very active.

**Comment by wilianmaique** [comment]
it's 8684, I'll test it, any bug I open a topic

**Comment by ScriptedSnark** [comment]
> it's 8684, I'll test it, any bug I open a topic

Fully compatible.

**Comment by wilianmaique** [comment]
to start we need to create a steam emulator, so we don't need steam.

**Comment by wilianmaique** [comment]
tested it, it worked, but still need steam

**Comment by ScriptedSnark** [comment]
> to start we need to create a steam emulator, so we don't need steam.

Why? It's not necessary and there are Steam LAN emulators. I am just reimplementing GoldSrc components.

**Comment by wilianmaique** [comment]
> > to start we need to create a steam emulator, so we don't need steam.
> 
> Why? It's not necessary and there are Steam LAN emulators. I am just reimplementing GoldSrc components.

I understand, but I think that needing 'steam' we can have problems

**Comment by ScriptedSnark** [comment]
> I understand, but I think that needing 'steam' we can have problems

Only engine requires steam authentication, not GoldSrc components.

**Comment by wilianmaique** [comment]
yes, but do you intend to create a 'no-steam' or just rewrite some components?, because if you want to rewrite components, the idea is to be 'independent' of 'steam', to become something 'own', not to mention that at some point you will need to fiddle with the 'engine'

**Comment by ScriptedSnark** [comment]
> yes, but do you intend to create a 'no-steam' or just rewrite some components?, because if you want to rewrite components, the idea is to be 'independent' of 'steam', to become something 'own', not to mention that at some point you will need to fiddle with the 'engine'

I don't understand you. GoldSrc components are independent of Steam. I am just reimplementing them because I think that modders need more extended SDK than original HL SDK 2.4
